cargo-features = ["edition2024"]

[package]
name = "deepsixr"
version = "0.1.0"
edition = "2024"

[dependencies]
i3_ipc = "0.16.0"
itertools = "0.13.0"
nix = { version = "0.29.0", features = ["fs"] }
thiserror = "1.0.61"
